version: "3"

services:

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - bitcoin
      - ganache

  bitcoin:
    image: ruimarinho/bitcoin-core:0.16
    command:
      -printtoconsole
      -regtest=1
      -txindex=1
      -listen=1
      -server=1
      -irc=0
      -dnsseed=0
      -upnp=0
      -port=8332
      -rpcport=8333
      -rpcallowip=172.0.0.0/8
      -rpcbind=0.0.0.0
      -rpcuser=cryptorpc
      -rpcpassword=local321

  ganache:
    build:
      context: .
      dockerfile: ./tests/docker/ganache.Dockerfile
    ports:
      - 8545:8545

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
